//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDnevnik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DnevnikEntities : DbContext
    {
        public DnevnikEntities()
            : base("name=DnevnikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ocene> Ocenes { get; set; }
        public virtual DbSet<Odeljenja> Odeljenjas { get; set; }
        public virtual DbSet<PredmetiPoOdeljenjima> PredmetiPoOdeljenjimas { get; set; }
        public virtual DbSet<Profesori> Profesoris { get; set; }
        public virtual DbSet<RazredniStaresina> RazredniStaresinas { get; set; }
        public virtual DbSet<TipOcene> TipOcenes { get; set; }
        public virtual DbSet<Ucenici> Ucenicis { get; set; }
        public virtual DbSet<ListaPredmeta> ListaPredmetas { get; set; }
    }
}
